model:
  name: logreg
  params:
    C: 1.0
    class_weight: balanced
    max_iter: 1000
    solver: lbfgs

sampling:
  strategy: none  # none | undersample | oversample

preprocess:
  kind: scale_amount_time  # none | scale_amount_time

calibration:
  method: isotonic  # isotonic | sigmoid

cv:
  n_splits: 5
  shuffle: true
  random_state: 42

threshold:
  optimize_for: cost  # cost | f1 | youden
  costs:
    fp: 1.0
    fn: 25.0
  grid:
    start: 0.0
    stop: 1.0
    num: 1001

metrics:
  ece_bins: 15

output_root: experiments